### ISSUE TITLE
Unable to instantiate HipchatClient

### ISSUE THREAD

**Issue by PeterSawyer** [KyleGobel/Hipchat-CS#24]
I have previously implemented an avatar sync with your API wrapper but have noticed it has been failing for a while on the following line of code: -

```
HipchatClient hipchat = new HipchatClient(Properties.Settings.Default.HipchatAuthToken);
```

we are now getting this exception: -

```
System.AggregateException: One or more errors occurred. ---> System.MissingFieldException: Field not found: 'ServiceStack.Text.JsConfig`1.DeSerializeFn'.
   at HipchatApiV2.HipchatClient.ConfigureSerializer()
   at Impromptunet.Helpers.CronTasks.HipchatAvatarImages.Execute() in C:\BuildAgent\work\2b2f6d9b458403fb\Impromptunet\Helpers\CronTasks\HipchatAvatarImages.cs:line 23
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at FluentScheduler.TaskManager.<>c__DisplayClassf.<StartTask>b__d()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.MissingFieldException: Field not found: 'ServiceStack.Text.JsConfig`1.DeSerializeFn'.
   at HipchatApiV2.HipchatClient.ConfigureSerializer()
   at Impromptunet.Helpers.CronTasks.HipchatAvatarImages.Execute() in C:\BuildAgent\work\2b2f6d9b458403fb\Impromptunet\Helpers\CronTasks\HipchatAvatarImages.cs:line 23
   at System.Threading.Tasks.Task.Execute()<---
```

This started erroring at the end of August 2015

**Comment by KyleGobel** [comment]
Hey Peter,
Are you using servicestack in your project at all?  The exception looks like there's a servicestack version mismatch somewhere going on

**Comment by PeterSawyer** [comment]
Howdy Kyle,

In my solution I have a test project which was referencing version 4.0.42, whereas, the main project was referencing version 4.0.50 from your Hipchat-CS.

Have performed a NuGet update on the test project.  And yep everything is now working great.

Thanks heaps.

Regards
Peter

**Comment by PeterSawyer** [comment]
So even though HipChat-CS has dependency on ServiceStack.Text >- 4.0.18 it will not work with 4.0.50

This is the screen where It wants to update,

![image](https://cloud.githubusercontent.com/assets/1000573/11492401/f989bf7a-9840-11e5-8f7e-ad6bd01ae9f7.png)

**Comment by KyleGobel** [comment]
Alright, I'll try to get around to updating to latest servicestack.text tonight and see if we can get a new version published.

**Comment by PeterSawyer** [comment]
Any update on this yet?  I am still having to manually avoid this issue.

**Comment by KyleGobel** [comment]
i updated to the latest servicestack and pushed out a new version, hopefully that fixes your issues

**Comment by PeterSawyer** [comment]
Thanks Kyle. Pulled latest and tested all good.  Cheers :+1:
