### ISSUE TITLE
Set topic on room failing

### ISSUE THREAD

**Issue by uNople** [KyleGobel/Hipchat-CS#9]
Using the API like this:
var client = new HipchatClient(Token);
client.SetTopic("Room Name", "Topic");

I get the following failure:
HipchatApiV2.Exceptions.HipchatWebException: 
Message: 'The request body cannot be parsed as valid JSON: Expecting value: line 1 column 1 (char 0)'
Type: 'Bad Request' ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at ServiceStack.HttpUtils.SendStringToUrl(String url, String method, String requestBody, String contentType, String accept, Action`1 requestFilter, Action`1 responseFilter)
   at ServiceStack.HttpUtils.PutJsonToUrl(String url, String json, Action`1 requestFilter, Action`1 responseFilter)
   at HipchatApiV2.HipchatClient.SetTopic(String roomName, String topic)
   --- End of inner exception stack trace ---
   at HipchatApiV2.HipchatClient.SetTopic(String roomName, String topic)
   at UserQuery.Main() in c:\Users\test\AppData\Local\Temp\LINQPad\_rzxmtrte\query_mamjej.cs:line 39

**Comment by KyleGobel** [comment]
Hey uNople, sorry this took me so long to get too.

Body was being passed as a string, so it wasn't being serialized into the correct format Hipchat expected.

Fixed in this commit f424f9a
